const dataPhrasalVerbs = [
    { id: 1, verb: "give up", meaning: "stop doing something", example: "He decided to {gap} smoking.", answer: "give up" },
    { id: 2, verb: "look forward to", meaning: "feel happy about something that is going to happen", example: "I {gap} seeing you.", answer: "look forward to" },
    { id: 3, verb: "put off", meaning: "delay or postpone", example: "They had to {gap} the meeting.", answer: "put off" },
    { id: 4, verb: "take after", meaning: "resemble an older relative", example: "She {gap} her mother.", answer: "takes after" },
    { id: 5, verb: "bring up", meaning: "mention a topic", example: "Why did you {gap} that subject?", answer: "bring up" },
    { id: 6, verb: "call off", meaning: "cancel an event", example: "We had to {gap} the picnic because of the rain.", answer: "call off" },
    { id: 7, verb: "come across", meaning: "find by chance", example: "While cleaning the attic yesterday, I {gap} some old photos.", answer: "came across" },
    { id: 8, verb: "turn out", meaning: "have a particular result", example: "The movie {gap} to be really good in the end.", answer: "turned out" },
    { id: 9, verb: "make up", meaning: "invent a story", example: "He likes to {gap} stories.", answer: "make up" },
    { id: 10, verb: "get along", meaning: "have a good relationship", example: "I {gap} well with my siblings.", answer: "get along" },
    { id: 11, verb: "break down", meaning: "stop functioning", example: "My car {gap} on the highway last night.", answer: "broke down" },
    { id: 12, verb: "catch on", meaning: "become popular", example: "I hope this new fashion doesn't {gap}.", answer: "catch on" },
    { id: 13, verb: "do away with", meaning: "abolish or discard", example: "They want to {gap} school uniforms.", answer: "do away with" },
    { id: 14, verb: "fall through", meaning: "fail to happen", example: "Unfortunately, our plans for the weekend {gap}.", answer: "fell through" },
    { id: 15, verb: "get over", meaning: "recover from an illness or disappointment", example: "It took her months to {gap} the flu.", answer: "get over" },
    { id: 16, verb: "hold up", meaning: "delay", example: "Heavy traffic {gap} my arrival yesterday.", answer: "held up" },
    { id: 17, verb: "look into", meaning: "investigate", example: "The police will {gap} the matter.", answer: "look into" },
    { id: 18, verb: "pass out", meaning: "faint", example: "It was so hot that she {gap} during the ceremony.", answer: "passed out" },
    { id: 19, verb: "run out of", meaning: "have none left", example: "We have {gap} milk.", answer: "run out of" },
    { id: 20, verb: "set up", meaning: "arrange or organize", example: "Let's {gap} a meeting for next week.", answer: "set up" },
    { id: 21, verb: "take off", meaning: "become successful quickly", example: "Her business really {gap} last year.", answer: "took off" },
    { id: 22, verb: "work out", meaning: "solve a problem", example: "We need to {gap} a solution.", answer: "work out" },
    { id: 23, verb: "back up", meaning: "support", example: "I will {gap} your story.", answer: "back up" },
    { id: 24, verb: "carry out", meaning: "perform a task", example: "The scientists {gap} an experiment last month.", answer: "carried out" },
    { id: 25, verb: "drop in", meaning: "visit unexpectedly", example: "Feel free to {gap} anytime.", answer: "drop in" },
    { id: 26, verb: "figure out", meaning: "understand or solve", example: "I can't {gap} this math problem.", answer: "figure out" },
    { id: 27, verb: "give in", meaning: "surrender or yield", example: "The authorities refused to {gap} to their demands.", answer: "give in" },
    { id: 28, verb: "hand out", meaning: "distribute", example: "Please {gap} these papers.", answer: "hand out" },
    { id: 29, verb: "keep up with", meaning: "stay at the same pace", example: "It's hard to {gap} the latest technology.", answer: "keep up with" },
    { id: 30, verb: "let down", meaning: "disappoint", example: "Don't {gap} your team.", answer: "let down" },
    { id: 31, verb: "make out", meaning: "manage to see or hear", example: "I couldn't {gap} what he was saying.", answer: "make out" },
    { id: 32, verb: "pass away", meaning: "die", example: "His grandfather {gap} last night.", answer: "passed away" },
    { id: 33, verb: "point out", meaning: "draw attention to", example: "She {gap} the mistakes in the document.", answer: "pointed out" },
    { id: 34, verb: "put up with", meaning: "tolerate", example: "I can't {gap} this noise anymore.", answer: "put up with" },
    { id: 35, verb: "run into", meaning: "meet unexpectedly", example: "I {gap} an old friend at the store yesterday.", answer: "ran into" },
    { id: 36, verb: "show off", meaning: "display proudly", example: "He always likes to {gap} his new car.", answer: "show off" },
    { id: 37, verb: "take up", meaning: "start a hobby", example: "I decided to {gap} tennis.", answer: "take up" },
    { id: 38, verb: "turn down", meaning: "reject an offer", example: "She had to {gap} the job.", answer: "turn down" },
    { id: 39, verb: "wear out", meaning: "make useless by wear", example: "These shoes will {gap} soon.", answer: "wear out" },
    { id: 40, verb: "bring about", meaning: "cause to happen", example: "The new manager {gap} many changes last quarter.", answer: "brought about" },
    { id: 41, verb: "come up with", meaning: "think of an idea", example: "He {gap} a brilliant plan yesterday.", answer: "came up with" },
    { id: 42, verb: "fall out", meaning: "argue and stop being friends", example: "They {gap} over a silly misunderstanding.", answer: "fell out" },
    { id: 43, verb: "get away with", meaning: "escape punishment", example: "The thief tried to {gap} the jewels.", answer: "get away with" },
    { id: 44, verb: "go off", meaning: "explode or ring", example: "My alarm didn't {gap} this morning.", answer: "go off" },
    { id: 45, verb: "look up to", meaning: "admire and respect", example: "I always {gap} my older sister.", answer: "look up to" },
    { id: 46, verb: "make up for", meaning: "compensate for", example: "I'll buy dinner to {gap} being late.", answer: "make up for" },
    { id: 47, verb: "put forward", meaning: "suggest an idea", example: "She {gap} a new proposal at the meeting.", answer: "put forward" },
    { id: 48, verb: "stand out", meaning: "be prominent or noticeable", example: "Her bright red hair made her {gap}.", answer: "stand out" },
    { id: 49, verb: "take back", meaning: "retract a statement", example: "I {gap} what I said earlier.", answer: "take back" },
    { id: 50, verb: "turn up", meaning: "appear unexpectedly", example: "He didn't {gap} for the meeting.", answer: "turn up" },
    { id: 51, verb: "bring in", meaning: "introduce a new law or system", example: "The government plans to {gap} new tax laws.", answer: "bring in" },
    { id: 52, verb: "catch up", meaning: "reach the same level as others", example: "I need to {gap} on my reading.", answer: "catch up" },
    { id: 53, verb: "draw up", meaning: "prepare a document", example: "The lawyer will {gap} a contract.", answer: "draw up" },
    { id: 54, verb: "fall apart", meaning: "break into pieces", example: "The old house is starting to {gap}.", answer: "fall apart" },
    { id: 55, verb: "get by", meaning: "manage to survive", example: "We can {gap} on just one salary.", answer: "get by" },
    { id: 56, verb: "go over", meaning: "review or check", example: "Let's {gap} the details once more.", answer: "go over" },
    { id: 57, verb: "leave out", meaning: "omit", example: "Don't {gap} any important details.", answer: "leave out" },
    { id: 58, verb: "look down on", meaning: "despise or feel superior to", example: "He shouldn't {gap} people.", answer: "look down on" },
    { id: 59, verb: "pass on", meaning: "transmit or give to someone else", example: "Please {gap} the message.", answer: "pass on" },
    { id: 60, verb: "pull through", meaning: "recover from a serious illness", example: "The doctor thinks she will {gap}.", answer: "pull through" },
    { id: 61, verb: "set off", meaning: "start a journey", example: "We will {gap} early tomorrow morning.", answer: "set off" },
    { id: 62, verb: "stand by", meaning: "support or remain loyal to", example: "I will {gap} you no matter what.", answer: "stand by" },
    { id: 63, verb: "take over", meaning: "take control", example: "A large corporation wants to {gap} the company.", answer: "take over" },
    { id: 64, verb: "tell off", meaning: "reprimand", example: "The teacher had to {gap} the noisy students.", answer: "tell off" },
    { id: 65, verb: "turn over", meaning: "flip or give control", example: "Please {gap} the page.", answer: "turn over" },
    { id: 66, verb: "bring down", meaning: "cause to fall or lose power", example: "The scandal could {gap} the government.", answer: "bring down" },
    { id: 67, verb: "clear up", meaning: "become bright or solve a mystery", example: "The weather should {gap} later.", answer: "clear up" },
    { id: 68, verb: "cut down on", meaning: "reduce consumption", example: "I need to {gap} sugar.", answer: "cut down on" },
    { id: 69, verb: "give off", meaning: "emit a smell or light", example: "The cheese {gap} a terrible smell.", answer: "gave off" },
    { id: 70, verb: "rule out", meaning: "exclude a possibility", example: "The police cannot {gap} foul play.", answer: "rule out" }
];

const dataCollocations = [
    { id: 1, part1: "make", part2: "an effort", hint: "To try hard" },
    { id: 2, part1: "do", part2: "your best", hint: "To perform as well as you can" },
    { id: 3, part1: "catch", part2: "someone's eye", hint: "To attract someone's attention" }
];
