const dataPart1 = [
    { id: 1, sentence: "People often {gap} out their cameras almost mindlessly to capture a moment.", options: ["whip", "pull", "draw", "drag"], answer: "whip" },
    { id: 2, sentence: "Students are expected to {gap} close attention to the instructions provided.", options: ["pay", "make", "do", "have"], answer: "pay" },
    { id: 3, sentence: "Smoking is {gap} forbidden in all areas of the hospital.", options: ["strictly", "heavily", "strongly", "deeply"], answer: "strictly" },
    { id: 4, sentence: "The campaign aims to {gap} awareness about environmental issues.", options: ["raise", "rise", "arise", "lift"], answer: "raise" },
    { id: 5, sentence: "You need to {gap} a concerted effort if you want to pass the exam.", options: ["make", "take", "do", "put"], answer: "make" },
    { id: 6, sentence: "It is {gap} unlikely that the company will recover from this financial crisis.", options: ["highly", "utterly", "entirely", "completely"], answer: "highly" },
    { id: 7, sentence: "The mayor was {gap} criticized for his failure to address the housing problem.", options: ["heavily", "strictly", "firmly", "severely"], answer: "heavily" },
    { id: 8, sentence: "Over five hundred athletes will {gap} part in this year's marathon.", options: ["take", "have", "get", "make"], answer: "take" },
    { id: 9, sentence: "The new manager plans to {gap} about significant changes in the department.", options: ["bring", "come", "go", "get"], answer: "bring" },
    { id: 10, sentence: "The bright colors of the advertisement are designed to {gap} the consumer's eye.", options: ["catch", "hold", "keep", "draw"], answer: "catch" },
    { id: 11, sentence: "Because of the {gap} traffic, we arrived late for the meeting.", options: ["heavy", "strong", "thick", "dense"], answer: "heavy" },
    { id: 12, sentence: "The board members remain {gap} concerned about the dropping sales figures.", options: ["deeply", "thoroughly", "entirely", "totally"], answer: "deeply" },
    { id: 13, sentence: "When she heard the tragic news, she immediately {gap} into tears.", options: ["burst", "break", "tear", "drop"], answer: "burst" },
    { id: 14, sentence: "You must {gap} in mind that the deadline is strictly enforced.", options: ["bear", "keep", "hold", "carry"], answer: "bear" },
    { id: 15, sentence: "The young athlete managed to {gap} a new world record in the 100m sprint.", options: ["set", "put", "lay", "place"], answer: "set" },
    { id: 16, sentence: "The storm managed to {gap} widespread damage to the coastal towns.", options: ["do", "make", "take", "give"], answer: "do" },
    { id: 17, sentence: "The new Thai restaurant in town is {gap} recommended by local food critics.", options: ["highly", "strictly", "absolutely", "strongly"], answer: "highly" },
    { id: 18, sentence: "He couldn't afford to {gap} such a golden opportunity to further his career.", options: ["miss", "lose", "drop", "fail"], answer: "miss" },
    { id: 19, sentence: "It is {gap} believed that the universe is constantly expanding.", options: ["widely", "broadly", "fully", "greatly"], answer: "widely" },
    { id: 20, sentence: "The dry wood quickly managed to {gap} fire and spread to the nearby trees.", options: ["catch", "set", "lay", "put"], answer: "catch" },
    { id: 21, sentence: "The customer was {gap} furious about the appalling service she received.", options: ["absolutely", "totally", "completely", "entirely"], answer: "absolutely" },
    { id: 22, sentence: "The expedition team began to {gap} short of supplies after a week in the mountains.", options: ["run", "go", "come", "fall"], answer: "run" },
    { id: 23, sentence: "The faulty wiring is likely to {gap} trouble if not replaced soon.", options: ["cause", "make", "do", "create"], answer: "cause" },
    { id: 24, sentence: "She was {gap} offended by his insensitive remarks at the dinner party.", options: ["deeply", "strongly", "heavily", "seriously"], answer: "deeply" },
    { id: 25, sentence: "It is difficult to {gap} a meaningful conversation with him when he is distracted.", options: ["hold", "keep", "stay", "remain"], answer: "hold" },
    { id: 26, sentence: "He is known as a man of his word and would never {gap} a promise.", options: ["break", "snap", "crack", "tear"], answer: "break" },
    { id: 27, sentence: "Anyone caught plagiarizing will be {gap} punished.", options: ["severely", "strongly", "heavily", "strictly"], answer: "severely" },
    { id: 28, sentence: "It is considered polite to {gap} someone a compliment on their work.", options: ["pay", "give", "show", "offer"], answer: "pay" },
    { id: 29, sentence: "Modern societies have become {gap} reliant on digital technology.", options: ["heavily", "highly", "deeply", "totally"], answer: "heavily" },
    { id: 30, sentence: "I assure you that I can {gap} a secret if you choose to confide in me.", options: ["keep", "hold", "catch", "stay"], answer: "keep" },
    { id: 31, sentence: "They had to {gap} a quick decision before the offer expired.", options: ["make", "take", "have", "give"], answer: "make" },
    { id: 32, sentence: "After a twelve-hour shift at the hospital, the nurse was {gap} exhausted.", options: ["utterly", "entirely", "widely", "completely"], answer: "utterly" },
    { id: 33, sentence: "The artist's peculiar style never fails to {gap} attention from critics.", options: ["draw", "pull", "catch", "grab"], answer: "draw" },
    { id: 34, sentence: "The new business venture turned out to be {gap} profitable.", options: ["highly", "broadly", "deeply", "strictly"], answer: "highly" },
    { id: 35, sentence: "It took her years to {gap} to terms with the loss of her childhood home.", options: ["come", "go", "run", "fall"], answer: "come" },
    { id: 36, sentence: "Companies are adopting AI to {gap} a competitive advantage in the market.", options: ["gain", "take", "get", "win"], answer: "gain" },
    { id: 37, sentence: "Learning to play the violin professionally is an {gap} difficult task.", options: ["incredibly", "absolutely", "strongly", "deeply"], answer: "incredibly" },
    { id: 38, sentence: "Despite working in the same city, the two friends managed to {gap} touch.", options: ["lose", "drop", "leave", "fall"], answer: "lose" },
    { id: 39, sentence: "The event was cancelled due to the surprisingly {gap} rain that morning.", options: ["heavy", "strong", "hard", "tough"], answer: "heavy" },
    { id: 40, sentence: "I {gap} believe that hard work and dedication eventually pay off.", options: ["firmly", "strictly", "deeply", "heavily"], answer: "firmly" },
    { id: 41, sentence: "Exposure to excessive radiation can {gap} irreparable harm to living cells.", options: ["do", "give", "make", "bring"], answer: "do" },
    { id: 42, sentence: "When she offered him the leading role, he didn't hesitate to {gap} the opportunity.", options: ["seize", "catch", "take", "grab"], answer: "seize" },
    { id: 43, sentence: "The management is {gap} aware of the issues raised by the union.", options: ["fully", "widely", "completely", "thoroughly"], answer: "fully" },
    { id: 44, sentence: "It is unfair to {gap} the blame on the junior staff for the systemic failures.", options: ["lay", "make", "put", "place"], answer: "lay" },
    { id: 45, sentence: "The vaccine is now {gap} available in most clinics across the country.", options: ["widely", "largely", "greatly", "highly"], answer: "widely" },
    { id: 46, sentence: "The suspect doesn't {gap} any resemblance to the sketch provided by the witness.", options: ["bear", "hold", "keep", "stand"], answer: "bear" },
    { id: 47, sentence: "The conditions in the factory were found to be {gap} unacceptable.", options: ["totally", "absolutely", "heavily", "deeply"], answer: "totally" },
    { id: 48, sentence: "If you don't wear a helmet, you {gap} a massive risk of serious injury.", options: ["run", "set", "take", "go"], answer: "run" },
    { id: 49, sentence: "The smartphone industry remains a {gap} competitive market.", options: ["fiercely", "highly", "utterly", "heavily"], answer: "fiercely" },
    { id: 50, sentence: "Try not to {gap} a mess in the kitchen while you're baking the cake.", options: ["make", "get", "do", "take"], answer: "make" },
    { id: 51, sentence: "The hotel was {gap} booked for the holiday weekend months in advance.", options: ["fully", "broadly", "widely", "wholly"], answer: "fully" },
    { id: 52, sentence: "It is often said that children cannot easily {gap} a lie from the truth.", options: ["tell", "give", "speak", "say"], answer: "tell" },
    { id: 53, sentence: "She is {gap} capable of completing the project without any supervision.", options: ["perfectly", "greatly", "highly", "entirely"], answer: "perfectly" },
    { id: 54, sentence: "Don't {gap} your breath waiting for an apology; he never admits when he's wrong.", options: ["hold", "keep", "have", "make"], answer: "hold" },
    { id: 55, sentence: "We would {gap} appreciate any feedback you can provide on our service.", options: ["greatly", "highly", "widely", "absolutely"], answer: "greatly" },
    { id: 56, sentence: "It is important to {gap} respect for the traditions of the country you are visiting.", options: ["show", "give", "make", "take"], answer: "show" },
    { id: 57, sentence: "He was {gap} disappointed when he failed to secure the promotion.", options: ["bitterly", "strictly", "utterly", "severely"], answer: "bitterly" },
    { id: 58, sentence: "If you go outside without a coat in this weather, you'll {gap} a cold.", options: ["catch", "take", "get", "fetch"], answer: "catch" },
    { id: 59, sentence: "The two languages are {gap} related and share many grammatical structures.", options: ["closely", "highly", "deeply", "tightly"], answer: "closely" },
    { id: 60, sentence: "The new experimental treatment is finally beginning to {gap} positive results.", options: ["yield", "give", "pay", "show"], answer: "yield" },
    { id: 61, sentence: "The contents of this document are {gap} confidential and must not be shared.", options: ["strictly", "fully", "absolutely", "highly"], answer: "strictly" },
    { id: 62, sentence: "The ongoing stress at work has begun to {gap} a heavy toll on her health.", options: ["take", "make", "do", "build"], answer: "take" },
    { id: 63, sentence: "Local residents are {gap} opposed to the construction of a new highway near their homes.", options: ["strongly", "heavily", "widely", "deeply"], answer: "strongly" },
    { id: 64, sentence: "She learned how to {gap} a successful business from her grandfather.", options: ["run", "manage", "rule", "control"], answer: "run" },
    { id: 65, sentence: "The laboratory is {gap} equipped to handle advanced genetic research.", options: ["fully", "entirely", "highly", "widely"], answer: "fully" },
    { id: 66, sentence: "The manager tends to {gap} too much pressure on the junior employees.", options: ["put", "make", "have", "give"], answer: "put" },
    { id: 67, sentence: "The committee was {gap} divided over how to allocate the remaining budget.", options: ["deeply", "totally", "bitterly", "widely"], answer: "deeply" },
    { id: 68, sentence: "Craftsmen typically {gap} great pride in the quality of their work.", options: ["take", "give", "have", "make"], answer: "take" },
    { id: 69, sentence: "It is {gap} essential that you submit your application before the deadline.", options: ["absolutely", "strictly", "fully", "heavily"], answer: "absolutely" },
    { id: 70, sentence: "The instructions are so confusing that they hardly {gap} any sense at all.", options: ["make", "do", "give", "take"], answer: "make" }
];

const dataPart2 = [
    { id: 1, sentence: "She insisted {gap} paying for dinner despite our objections.", answer: "on" },
    { id: 2, sentence: "I am not used {gap} waking up so early in the morning.", answer: "to" },
    { id: 3, sentence: "He finally decided to give {gap} smoking for the sake of his health.", answer: "up" },
    { id: 4, sentence: "She has always been particularly interested {gap} ancient history.", answer: "in" },
    { id: 5, sentence: "We look {gap} to welcoming you to our hotel next week.", answer: "forward" },
    { id: 6, sentence: "They proved that they were entirely capable {gap} managing the project alone.", answer: "of" },
    { id: 7, sentence: "The manager had to apologize {gap} the unexpected delay in delivery.", answer: "for" },
    { id: 8, sentence: "Researchers plan to carry {gap} further experiments to verify their hypothesis.", answer: "out" },
    { id: 9, sentence: "The new regulations are designed to prevent the disease {gap} spreading.", answer: "from" },
    { id: 10, sentence: "She had to turn {gap} the job offer because the salary was too low.", answer: "down" },
    { id: 11, sentence: "Customers who are not satisfied {gap} the product can claim a full refund.", answer: "with" },
    { id: 12, sentence: "Many teenagers today are addicted {gap} their smartphones.", answer: "to" },
    { id: 13, sentence: "We were quite surprised {gap} the sudden change in the weather.", answer: "at" },
    { id: 14, sentence: "The team leader is ultimately responsible {gap} the success of the project.", answer: "for" },
    { id: 15, sentence: "It took them weeks to find {gap} the truth about what happened that night.", answer: "out" },
    { id: 16, sentence: "Failure to follow the safety guidelines could result {gap} serious injury.", answer: "in" },
    { id: 17, sentence: "Are you fully aware {gap} the risks involved in this investment?", answer: "of" },
    { id: 18, sentence: "You must take {gap} account the extra costs when planning your budget.", answer: "into" },
    { id: 19, sentence: "In rural areas, many communities rely entirely {gap} farming for survival.", answer: "on" },
    { id: 20, sentence: "She had to make {gap} an excuse for being late to the meeting.", answer: "up" },
    { id: 21, sentence: "Many people in the region suffer {gap} acute respiratory problems.", answer: "from" },
    { id: 22, sentence: "I strongly object {gap} being treated as if I were a child.", answer: "to" },
    { id: 23, sentence: "To succeed {gap} business, you need both passion and perseverance.", answer: "in" },
    { id: 24, sentence: "Her bright red hair made her stand {gap} in the crowd.", answer: "out" },
    { id: 25, sentence: "He quickly became accustomed {gap} the cold climate of Scandinavia.", answer: "to" },
    { id: 26, sentence: "My grandfather was incredibly fond {gap} classical music.", answer: "of" },
    { id: 27, sentence: "She found it increasingly difficult to cope {gap} the stress of her new job.", answer: "with" },
    { id: 28, sentence: "Due to heavy snow, they had to put {gap} the match until next week.", answer: "off" },
    { id: 29, sentence: "Hundreds of people are expected to apply {gap} the new management position.", answer: "for" },
    { id: 30, sentence: "Ever since he was a child, he has been brilliant {gap} solving puzzles.", answer: "at" },
    { id: 31, sentence: "Please turn off the television so I can concentrate {gap} my studies.", answer: "on" },
    { id: 32, sentence: "Despite the lack of evidence, she firmly believes {gap} ghosts.", answer: "in" },
    { id: 33, sentence: "The teacher pointed {gap} several mistakes in my essay.", answer: "out" },
    { id: 34, sentence: "He was falsely accused {gap} stealing the money from the safe.", answer: "of" },
    { id: 35, sentence: "You can't blame me {gap} the mistake; I wasn't even there.", answer: "for" },
    { id: 36, sentence: "It's difficult to bring {gap} children in such a fast-paced society.", answer: "up" },
    { id: 37, sentence: "She decided to dedicate her life {gap} helping the underprivileged.", answer: "to" },
    { id: 38, sentence: "Many English words derive {gap} Latin or Greek roots.", answer: "from" },
    { id: 39, sentence: "It took them a long time to work {gap} a solution to the complex problem.", answer: "out" },
    { id: 40, sentence: "The jury eventually found him guilty {gap} all charges.", answer: "of" },
    { id: 41, sentence: "Please do not let your personal issues interfere {gap} your professional duties.", answer: "with" },
    { id: 42, sentence: "The authorities have promised to look {gap} the matter immediately.", answer: "into" },
    { id: 43, sentence: "The term 'artificial intelligence' was first referred {gap} in the 1950s.", answer: "to" },
    { id: 44, sentence: "It's never too early to start investing {gap} a pension plan.", answer: "in" },
    { id: 45, sentence: "The success of the festival will largely depend {gap} the weather.", answer: "on" },
    { id: 46, sentence: "I need to study this weekend to catch {gap} on the lessons I missed.", answer: "up" },
    { id: 47, sentence: "The prisoners were deprived {gap} sleep for several consecutive days.", answer: "of" },
    { id: 48, sentence: "There is absolutely no excuse {gap} such rude behavior.", answer: "for" },
    { id: 49, sentence: "We have unfortunately run {gap} of printer ink.", answer: "out" },
    { id: 50, sentence: "I called to congratulate her {gap} passing her driving test.", answer: "on" },
    { id: 51, sentence: "It took him nearly a year to recover {gap} the severe injuries.", answer: "from" },
    { id: 52, sentence: "The organizers had to call {gap} the outdoor concert due to rain.", answer: "off" },
    { id: 53, sentence: "After his degree, he decided to specialize {gap} pediatric medicine.", answer: "in" },
    { id: 54, sentence: "Everyone in the team is expected to contribute {gap} the discussion.", answer: "to" },
    { id: 55, sentence: "They are planning to set {gap} a charity to help homeless youths.", answer: "up" },
    { id: 56, sentence: "Her parents do not approve {gap} her decision to drop out of college.", answer: "of" },
    { id: 57, sentence: "The university aims to provide students {gap} the skills they need to succeed.", answer: "with" },
    { id: 58, sentence: "He felt terrible that he had let his friends {gap} when they needed him most.", answer: "down" },
    { id: 59, sentence: "The movie is loosely based {gap} a true story from the 19th century.", answer: "on" },
    { id: 60, sentence: "The manager couldn't account {gap} the missing funds.", answer: "for" },
    { id: 61, sentence: "When the war broke {gap}, many families were forced to flee their homes.", answer: "out" },
    { id: 62, sentence: "Regular exercise is known to benefit people {gap} all ages.", answer: "of" },
    { id: 63, sentence: "Several high-profile politicians were involved {gap} the scandal.", answer: "in" },
    { id: 64, sentence: "The thieves managed to get {gap} with a substantial amount of jewelry.", answer: "away" },
    { id: 65, sentence: "The patient failed to respond {gap} the initial treatment.", answer: "to" },
    { id: 66, sentence: "While I sympathize {gap} your situation, there is nothing I can do to help.", answer: "with" },
    { id: 67, sentence: "The police have not yet ruled {gap} the possibility of arson.", answer: "out" },
    { id: 68, sentence: "The exhibition will consist {gap} over fifty original paintings.", answer: "of" },
    { id: 69, sentence: "You can always count {gap} him to help out in an emergency.", answer: "on" },
    { id: 70, sentence: "We waited for an hour, but he never turned {gap}.", answer: "up" }
];
