const dataPart3 = [
    { id: 1, sentence: "The {gap} of the new shopping centre caused much debate. (DEVELOP)", root: "DEVELOP", answer: "development" },
    { id: 2, sentence: "His explanation was highly {gap}, so nobody believed him. (PROBABLE)", root: "PROBABLE", answer: "improbable" },
    { id: 3, sentence: "She showed great {gap} in the face of danger. (BRAVE)", root: "BRAVE", answer: "bravery" },
    { id: 4, sentence: "The results of the test were completely {gap}. (EXPECT)", root: "EXPECT", answer: "unexpected" },
    { id: 5, sentence: "There has been a significant {gap} in sales this year. (REDUCE)", root: "REDUCE", answer: "reduction" },
    { id: 6, sentence: "I have no {gap} of resigning from my current position. (INTEND)", root: "INTEND", answer: "intention" },
    { id: 7, sentence: "The {gap} of the species is threatened by climate change. (SURVIVE)", root: "SURVIVE", answer: "survival" },
    { id: 8, sentence: "He was {gap} dismissed from his job for arriving late. (SUMMARY)", root: "SUMMARY", answer: "summarily" },
    { id: 9, sentence: "It was extremely {gap} of you to leave the door unlocked. (CARE)", root: "CARE", answer: "careless" },
    { id: 10, sentence: "The {gap} of the new museum will take place next week. (OPEN)", root: "OPEN", answer: "opening" },
    { id: 11, sentence: "Her {gap} to help us was a pleasant surprise. (WILLING)", root: "WILLING", answer: "willingness" },
    { id: 12, sentence: "They were deeply {gap} with the service at the restaurant. (SATISFY)", root: "SATISFY", answer: "dissatisfied" },
    { id: 13, sentence: "The {gap} of the virus can be prevented by basic hygiene. (INFECT)", root: "INFECT", answer: "infection" },
    { id: 14, sentence: "We need to find a {gap} to this problem soon. (SOLVE)", root: "SOLVE", answer: "solution" },
    { id: 15, sentence: "His {gap} of the subject is truly impressive. (KNOW)", root: "KNOW", answer: "knowledge" },
    { id: 16, sentence: "The instructions were completely {gap}, which led to confusion. (COMPREHEND)", root: "COMPREHEND", answer: "incomprehensible" },
    { id: 17, sentence: "There is a strong {gap} that the meeting will be cancelled. (LIKELY)", root: "LIKELY", answer: "likelihood" },
    { id: 18, sentence: "She has a {gap} to exaggerate her achievements. (TEND)", root: "TEND", answer: "tendency" },
    { id: 19, sentence: "The sudden {gap} of the storm caught everyone off guard. (ARRIVE)", root: "ARRIVE", answer: "arrival" },
    { id: 20, sentence: "His {gap} in the project was crucial to its success. (INVOLVE)", root: "INVOLVE", answer: "involvement" },
    { id: 21, sentence: "The {gap} of the building was delayed due to bad weather. (CONSTRUCT)", root: "CONSTRUCT", answer: "construction" },
    { id: 22, sentence: "She has a very {gap} personality towards animals. (AFFECTION)", root: "AFFECTION", answer: "affectionate" },
    { id: 23, sentence: "The {gap} of the new policy was met with protests. (INTRODUCE)", root: "INTRODUCE", answer: "introduction" },
    { id: 24, sentence: "He gave a highly {gap} speech that inspired everyone. (MOTIVATE)", root: "MOTIVATE", answer: "motivational" },
    { id: 25, sentence: "The {gap} of the committee is still unknown. (DECIDE)", root: "DECIDE", answer: "decision" },
    { id: 26, sentence: "She looked at him in {gap} when he told the joke. (AMUSE)", root: "AMUSE", answer: "amusement" },
    { id: 27, sentence: "The {gap} of the forest is essential for wildlife. (PRESERVE)", root: "PRESERVE", answer: "preservation" },
    { id: 28, sentence: "His {gap} to authority often got him into trouble. (RESIST)", root: "RESIST", answer: "resistance" },
    { id: 29, sentence: "The {gap} of the artist's work is widely recognized. (BRILLIANT)", root: "BRILLIANT", answer: "brilliance" },
    { id: 30, sentence: "She spoke {gap} about her experiences abroad. (PASSION)", root: "PASSION", answer: "passionately" },
    { id: 31, sentence: "The {gap} of the new software has caused many issues. (INSTALL)", root: "INSTALL", answer: "installation" },
    { id: 32, sentence: "He is very {gap} about his privacy online. (PROTECT)", root: "PROTECT", answer: "protective" },
    { id: 33, sentence: "The {gap} of the old monument took several years. (RESTORE)", root: "RESTORE", answer: "restoration" },
    { id: 34, sentence: "She gave a {gap} performance in the play. (REMARK)", root: "REMARK", answer: "remarkable" },
    { id: 35, sentence: "The {gap} of the new rules caused a lot of confusion. (APPLY)", root: "APPLY", answer: "application" },
    { id: 36, sentence: "He is a very {gap} young musician. (PROMISE)", root: "PROMISE", answer: "promising" },
    { id: 37, sentence: "The {gap} of the bridge was a marvel of engineering. (CREATE)", root: "CREATE", answer: "creation" },
    { id: 38, sentence: "She looked completely {gap} after the long journey. (EXHAUST)", root: "EXHAUST", answer: "exhausted" },
    { id: 39, sentence: "The {gap} of the document was unquestionable. (AUTHENTIC)", root: "AUTHENTIC", answer: "authenticity" },
    { id: 40, sentence: "He was {gap} unaware of the danger he was in. (BLISS)", root: "BLISS", answer: "blissfully" },
    { id: 41, sentence: "The {gap} of the town has increased significantly. (POPULATE)", root: "POPULATE", answer: "population" },
    { id: 42, sentence: "She has a strong {gap} for classical music. (PREFER)", root: "PREFER", answer: "preference" },
    { id: 43, sentence: "The {gap} of the new law was welcomed by many. (ENACT)", root: "ENACT", answer: "enactment" },
    { id: 44, sentence: "He is known for his {gap} and generosity. (KIND)", root: "KIND", answer: "kindness" },
    { id: 45, sentence: "The {gap} of the experiment were published in a journal. (FIND)", root: "FIND", answer: "findings" },
    { id: 46, sentence: "She showed great {gap} in solving the puzzle. (CLEVER)", root: "CLEVER", answer: "cleverness" },
    { id: 47, sentence: "The {gap} of the new system will improve efficiency. (IMPLEMENT)", root: "IMPLEMENT", answer: "implementation" },
    { id: 48, sentence: "He gave a {gap} description of the suspect to the police. (DETAIL)", root: "DETAIL", answer: "detailed" },
    { id: 49, sentence: "The {gap} of the two companies was announced today. (MERGE)", root: "MERGE", answer: "merger" },
    { id: 50, sentence: "She looked at him with {gap} when he suggested the idea. (SUSPECT)", root: "SUSPECT", answer: "suspicion" },
    { id: 51, sentence: "The {gap} of the book was delayed by the publisher. (PUBLISH)", root: "PUBLISH", answer: "publication" },
    { id: 52, sentence: "He has a very {gap} approach to problem-solving. (PRACTICE)", root: "PRACTICE", answer: "practical" },
    { id: 53, sentence: "The {gap} of the new product was a huge success. (INNOVATE)", root: "INNOVATE", answer: "innovation" },
    { id: 54, sentence: "She gave a {gap} account of her travels. (FASCINATE)", root: "FASCINATE", answer: "fascinating" },
    { id: 55, sentence: "There is a {gap} lack of resources in the area. (NOTICE)", root: "NOTICE", answer: "noticeable" },
    { id: 56, sentence: "He is a very {gap} worker under pressure. (RELY)", root: "RELY", answer: "reliable" },
    { id: 57, sentence: "The {gap} of the new school was celebrated by the town. (COMPLETE)", root: "COMPLETE", answer: "completion" },
    { id: 58, sentence: "She looked {gap} at the mess on the floor. (DISGUST)", root: "DISGUST", answer: "disgustedly" },
    { id: 59, sentence: "The film's {gap} of the classic novel was astonishing. (ADAPT)", root: "ADAPT", answer: "adaptation" },
    { id: 60, sentence: "He gave a {gap} smile before leaving the room. (MYSTERY)", root: "MYSTERY", answer: "mysterious" },
    { id: 61, sentence: "The {gap} of the company led to many job losses. (BANKRUPT)", root: "BANKRUPT", answer: "bankruptcy" },
    { id: 62, sentence: "She is highly {gap} in several programming languages. (PROFICIENCY)", root: "PROFICIENCY", answer: "proficient" },
    { id: 63, sentence: "His {gap} was unquestioned by the jury. (HONEST)", root: "HONEST", answer: "honesty" },
    { id: 64, sentence: "He gave a {gap} apology for his behavior. (SINCERE)", root: "SINCERE", answer: "sincere" },
    { id: 65, sentence: "The {gap} of the stadium was impressive and cost millions. (EXPAND)", root: "EXPAND", answer: "expansion" },
    { id: 66, sentence: "She looked completely {gap} by his complex comments. (BEWILDER)", root: "BEWILDER", answer: "bewildered" },
    { id: 67, sentence: "The {gap} of the new manager brought many changes. (APPOINT)", root: "APPOINT", answer: "appointment" },
    { id: 68, sentence: "He has a very {gap} personality and always takes control. (DOMINATE)", root: "DOMINATE", answer: "domineering" },
    { id: 69, sentence: "The {gap} of the evidence was crucial to the case. (RELY)", root: "RELY", answer: "reliability" },
    { id: 70, sentence: "It was a major {gap} that cost the company its reputation. (JUDGE)", root: "JUDGE", answer: "misjudgment" }
];

const dataPart4 = [
    { id: 1, original: "I'm sure she was at the party.", keyword: "MUST", prompt: "She", end: "at the party.", answer: "must have been" },
    { id: 2, original: "They are repairing my car today.", keyword: "HAVING", prompt: "I", end: "today.", answer: "am having my car repaired" },
    { id: 3, original: "I regret not studying harder.", keyword: "ONLY", prompt: "If", end: "harder.", answer: "only I had studied" },
    { id: 4, original: "He didn't go because he was tired.", keyword: "GONE", prompt: "He", end: "he hadn't been tired.", answer: "would have gone if" },
    { id: 5, original: "They believe the thief has left the country.", keyword: "THOUGHT", prompt: "The thief", end: "the country.", answer: "is thought to have left" },
    { id: 6, original: "I have never seen such a beautiful sunset.", keyword: "BEFORE", prompt: "Never", end: "such a beautiful sunset.", answer: "before have I seen" },
    { id: 7, original: "She started working here three years ago.", keyword: "BEEN", prompt: "She", end: "three years.", answer: "has been working here for" },
    { id: 8, original: "He is too young to drive a car.", keyword: "OLD", prompt: "He", end: "to drive a car.", answer: "is not old enough" },
    { id: 9, original: "It was a mistake for you to buy that car.", keyword: "BOUGHT", prompt: "You", end: "that car.", answer: "should not have bought" },
    { id: 10, original: "I prefer staying in to going out.", keyword: "RATHER", prompt: "I", end: "go out.", answer: "would rather stay in than" },
    { id: 11, original: "They will probably win the match.", keyword: "LIKELY", prompt: "They", end: "the match.", answer: "are likely to win" },
    { id: 12, original: "Someone stole my bike yesterday.", keyword: "HAD", prompt: "I", end: "yesterday.", answer: "had my bike stolen" },
    { id: 13, original: "I'm sure he didn't mean to hurt you.", keyword: "MEANT", prompt: "He", end: "to hurt you.", answer: "can't have meant" },
    { id: 14, original: "She is the most intelligent person I know.", keyword: "AS", prompt: "No one I know", end: "she is.", answer: "is as intelligent as" },
    { id: 15, original: "He promised to call me as soon as he arrived.", keyword: "WORD", prompt: "He", end: "call me as soon as he arrived.", answer: "gave me his word to" },
    { id: 16, original: "I don't want to go to the cinema tonight.", keyword: "FEEL", prompt: "I", end: "to the cinema tonight.", answer: "don't feel like going" },
    { id: 17, original: "It's a pity you didn't tell me earlier.", keyword: "WISH", prompt: "I", end: "me earlier.", answer: "wish you had told" },
    { id: 18, original: "They forced him to sign the contract.", keyword: "MADE", prompt: "He", end: "the contract.", answer: "was made to sign" },
    { id: 19, original: "I'm sure she's not at home now.", keyword: "BE", prompt: "She", end: "at home now.", answer: "can't be" },
    { id: 20, original: "He succeeded in passing the exam.", keyword: "MANAGED", prompt: "He", end: "the exam.", answer: "managed to pass" },
    { id: 21, original: "They say the company is losing money.", keyword: "SAID", prompt: "The company", end: "money.", answer: "is said to be losing" },
    { id: 22, original: "I've never eaten such a delicious meal.", keyword: "EVER", prompt: "It's the most", end: "eaten.", answer: "delicious meal I have ever" },
    { id: 23, original: "She didn't want to talk about it.", keyword: "OBJECTED", prompt: "She", end: "about it.", answer: "objected to talking" },
    { id: 24, original: "He is always interrupting me.", keyword: "KEEPS", prompt: "He", end: "me.", answer: "keeps on interrupting" },
    { id: 25, original: "I'm sorry I offended you.", keyword: "APOLOGIZE", prompt: "I", end: "you.", answer: "apologize for offending" },
    { id: 26, original: "They let him go after questioning.", keyword: "ALLOWED", prompt: "He", end: "after questioning.", answer: "was allowed to go" },
    { id: 27, original: "She didn't know how to swim until she was ten.", keyword: "WHEN", prompt: "It", end: "she learned how to swim.", answer: "was only when she was ten that" },
    { id: 28, original: "He couldn't find his keys anywhere.", keyword: "NOWHERE", prompt: "His keys", end: "found.", answer: "were nowhere to be" },
    { id: 29, original: "I suggest you take a taxi.", keyword: "ADVISE", prompt: "I", end: "a taxi.", answer: "advise you to take" },
    { id: 30, original: "The weather was so bad that we couldn't go out.", keyword: "SUCH", prompt: "It", end: "we couldn't go out.", answer: "was such bad weather that" },
    { id: 31, original: "I'm sure it was John who broke the window.", keyword: "MUST", prompt: "It", end: "who broke the window.", answer: "must have been John" },
    { id: 32, original: "They will complete the project by Friday.", keyword: "FINISHED", prompt: "The project", end: "by Friday.", answer: "will have been finished" },
    { id: 33, original: "I regret saying that to her.", keyword: "WISH", prompt: "I", end: "that to her.", answer: "wish I hadn't said" },
    { id: 34, original: "He is too short to reach the top shelf.", keyword: "TALL", prompt: "He", end: "to reach the top shelf.", answer: "isn't tall enough" },
    { id: 35, original: "I prefer tea to coffee.", keyword: "DRINK", prompt: "I", end: "coffee.", answer: "would rather drink tea than" },
    { id: 36, original: "She started learning French two years ago.", keyword: "STUDYING", prompt: "She", end: "two years.", answer: "has been studying French for" },
    { id: 37, original: "It's a mistake to think it's easy.", keyword: "WOULD", prompt: "It", end: "to think it's easy.", answer: "would be a mistake" },
    { id: 38, original: "They made her wait for two hours.", keyword: "WAS", prompt: "She", end: "for two hours.", answer: "was made to wait" },
    { id: 39, original: "I'm sure they haven't left yet.", keyword: "HAVE", prompt: "They", end: "yet.", answer: "can't have left" },
    { id: 40, original: "He managed to convince them.", keyword: "SUCCEEDED", prompt: "He", end: "them.", answer: "succeeded in convincing" },
    { id: 41, original: "People believe he is living abroad.", keyword: "BELIEVED", prompt: "He", end: "abroad.", answer: "is believed to be living" },
    { id: 42, original: "I don't want to discuss it now.", keyword: "RATHER", prompt: "I", end: "it now.", answer: "would rather not discuss" },
    { id: 43, original: "She didn't go out because it was raining.", keyword: "GONE", prompt: "If it hadn't been raining, she", end: "out.", answer: "would have gone" },
    { id: 44, original: "He was the first to arrive.", keyword: "ARRIVED", prompt: "He", end: "first.", answer: "was the person who arrived" },
    { id: 45, original: "I'm sorry I didn't help you.", keyword: "REGRET", prompt: "I", end: "you.", answer: "regret not helping" },
    { id: 46, original: "They allowed us to leave early.", keyword: "LET", prompt: "They", end: "early.", answer: "let us leave" },
    { id: 47, original: "She didn't realize the danger until later.", keyword: "WHEN", prompt: "It", end: "she realized the danger.", answer: "was only later when" },
    { id: 48, original: "He couldn't solve the problem.", keyword: "INCAPABLE", prompt: "He", end: "the problem.", answer: "was incapable of solving" },
    { id: 49, original: "I advise you to see a doctor.", keyword: "BETTER", prompt: "You", end: "a doctor.", answer: "had better see" },
    { id: 50, original: "The book was so boring I couldn't finish it.", keyword: "SUCH", prompt: "It", end: "I couldn't finish it.", answer: "was such a boring book that" },
    { id: 51, original: "I'm sure you dropped your wallet here.", keyword: "MUST", prompt: "You", end: "here.", answer: "must have dropped your wallet" },
    { id: 52, original: "They will have built the house by next year.", keyword: "COMPLETED", prompt: "The house", end: "by next year.", answer: "will have been completed" },
    { id: 53, original: "I wish I had brought my umbrella.", keyword: "ONLY", prompt: "If", end: "my umbrella.", answer: "only I had brought" },
    { id: 54, original: "He is not old enough to vote.", keyword: "TOO", prompt: "He", end: "to vote.", answer: "is too young" },
    { id: 55, original: "I prefer reading to watching TV.", keyword: "READ", prompt: "I", end: "watch TV.", answer: "would rather read than" },
    { id: 56, original: "She started writing the novel a year ago.", keyword: "BEEN", prompt: "She", end: "a year.", answer: "has been writing the novel for" },
    { id: 57, original: "It's wrong to assume he's guilty.", keyword: "MISTAKE", prompt: "It's", end: "assume he's guilty.", answer: "a mistake to" },
    { id: 58, original: "They forced him to confess.", keyword: "MADE", prompt: "He", end: "confess.", answer: "was made to" },
    { id: 59, original: "I'm certain she didn't take the money.", keyword: "TAKEN", prompt: "She", end: "the money.", answer: "can't have taken" },
    { id: 60, original: "He succeeded in finishing the race.", keyword: "ABLE", prompt: "He", end: "the race.", answer: "was able to finish" },
    { id: 61, original: "People say the house is haunted.", keyword: "SAID", prompt: "The house", end: "haunted.", answer: "is said to be" },
    { id: 62, original: "I don't want you to tell anyone.", keyword: "RATHER", prompt: "I", end: "tell anyone.", answer: "would rather you didn't" },
    { id: 63, original: "He didn't pass because he didn't study.", keyword: "PASSED", prompt: "If he had studied, he", end: ".", answer: "would have passed" },
    { id: 64, original: "She was the only one who understood.", keyword: "APART", prompt: "No one", end: "understood.", answer: "apart from her" },
    { id: 65, original: "I apologize for being late.", keyword: "SORRY", prompt: "I", end: "late.", answer: "am sorry for being" },
    { id: 66, original: "They let him stay overnight.", keyword: "ALLOWED", prompt: "He", end: "overnight.", answer: "was allowed to stay" },
    { id: 67, original: "She didn't know the answer until the end.", keyword: "WHEN", prompt: "It", end: "she knew the answer.", answer: "was only at the end when" },
    { id: 68, original: "He couldn't lift the heavy box.", keyword: "UNABLE", prompt: "He", end: "the heavy box.", answer: "was unable to lift" },
    { id: 69, original: "I suggest you take a break.", keyword: "ADVISE", prompt: "I", end: "a break.", answer: "advise you to take" },
    { id: 70, original: "The movie was so good I watched it twice.", keyword: "SUCH", prompt: "It", end: "I watched it twice.", answer: "was such a good movie that" }
];
